services:
  - type: web
    name: shadxmini-api
    env: node
    plan: starter
    region: frankfurt # or oregon / ohio
    nodeVersion: "20.18.0"
    buildCommand: pnpm install --no-frozen-lockfile && pnpm run build
    startCommand: pnpm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3000"
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: CLIENT_URL
        sync: false
      - key: TELEGRAM_STORE_BOT_TOKEN
        sync: false
